timezone: UTC
encoding: utf-8
title: Tastycat
url: https://tastycat.org/old_site

collections:
  rdjs:
    output: true
    permalink: /rdj/:path/
  staff:
      output: true
      permalink: /staff/:path/
  rules:
      output: false
  faqs:
        output: false
  events:
        output: true
        permalink: /event/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: rdjs
    values:
      layout: bio-rdj
  - scope:
      path: ""
      type: staff
    values:
      layout: bio-staff
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: events
    values:
      layout: event

exclude:
- CNAME
- Gemfile
- CONTRIBUTING.md
- LICENSE
- README.md

gems:
  - jekyll-sitemap
